/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustAndSafetyRouteImport } from './routes/trust-and-safety'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForPhotographersRouteImport } from './routes/for-photographers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClaimAccountRouteImport } from './routes/claim-account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GigsIndexRouteImport } from './routes/gigs.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as GigsIdRouteImport } from './routes/gigs.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedInquiriesIndexRouteImport } from './routes/_authenticated/inquiries.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as CCategoryCityRouteImport } from './routes/c.$category.$city'
import { Route as AuthenticatedStudioReviewsRouteImport } from './routes/_authenticated/studio.reviews'
import { Route as AuthenticatedStudioPortfolioRouteImport } from './routes/_authenticated/studio.portfolio'
import { Route as AuthenticatedStudioPackagesRouteImport } from './routes/_authenticated/studio.packages'
import { Route as AuthenticatedStudioLeadsRouteImport } from './routes/_authenticated/studio.leads'
import { Route as AuthenticatedStudioGigsRouteImport } from './routes/_authenticated/studio.gigs'
import { Route as AuthenticatedStudioEarningsRouteImport } from './routes/_authenticated/studio.earnings'
import { Route as AuthenticatedStudioDeliverablesRouteImport } from './routes/_authenticated/studio.deliverables'
import { Route as AuthenticatedStudioBookingsRouteImport } from './routes/_authenticated/studio.bookings'
import { Route as AuthenticatedStudioBillingRouteImport } from './routes/_authenticated/studio.billing'
import { Route as AuthenticatedStudioAvailabilityRouteImport } from './routes/_authenticated/studio.availability'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedInquiriesIdRouteImport } from './routes/_authenticated/inquiries.$id'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as AuthenticatedAdminVerificationRouteImport } from './routes/_authenticated/admin.verification'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPortfolioReportsRouteImport } from './routes/_authenticated/admin.portfolio-reports'
import { Route as AuthenticatedAdminPhotographersRouteImport } from './routes/_authenticated/admin.photographers'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminImageryRouteImport } from './routes/_authenticated/admin.imagery'
import { Route as AuthenticatedAdminGenresRouteImport } from './routes/_authenticated/admin.genres'
import { Route as AuthenticatedAdminFeaturedRouteImport } from './routes/_authenticated/admin.featured'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/admin.cities'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'

const TrustAndSafetyRoute = TrustAndSafetyRouteImport.update({
  id: '/trust-and-safety',
  path: '/trust-and-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPhotographersRoute = ForPhotographersRouteImport.update({
  id: '/for-photographers',
  path: '/for-photographers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimAccountRoute = ClaimAccountRouteImport.update({
  id: '/claim-account',
  path: '/claim-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIndexRoute = GigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/gigs/$id',
  path: '/gigs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiriesIndexRoute =
  AuthenticatedInquiriesIndexRouteImport.update({
    id: '/inquiries/',
    path: '/inquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const CCategoryCityRoute = CCategoryCityRouteImport.update({
  id: '/c/$category/$city',
  path: '/c/$category/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioReviewsRoute =
  AuthenticatedStudioReviewsRouteImport.update({
    id: '/studio/reviews',
    path: '/studio/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioPortfolioRoute =
  AuthenticatedStudioPortfolioRouteImport.update({
    id: '/studio/portfolio',
    path: '/studio/portfolio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioPackagesRoute =
  AuthenticatedStudioPackagesRouteImport.update({
    id: '/studio/packages',
    path: '/studio/packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioLeadsRoute =
  AuthenticatedStudioLeadsRouteImport.update({
    id: '/studio/leads',
    path: '/studio/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioGigsRoute = AuthenticatedStudioGigsRouteImport.update({
  id: '/studio/gigs',
  path: '/studio/gigs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioEarningsRoute =
  AuthenticatedStudioEarningsRouteImport.update({
    id: '/studio/earnings',
    path: '/studio/earnings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioDeliverablesRoute =
  AuthenticatedStudioDeliverablesRouteImport.update({
    id: '/studio/deliverables',
    path: '/studio/deliverables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioBookingsRoute =
  AuthenticatedStudioBookingsRouteImport.update({
    id: '/studio/bookings',
    path: '/studio/bookings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioBillingRoute =
  AuthenticatedStudioBillingRouteImport.update({
    id: '/studio/billing',
    path: '/studio/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioAvailabilityRoute =
  AuthenticatedStudioAvailabilityRouteImport.update({
    id: '/studio/availability',
    path: '/studio/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiriesIdRoute =
  AuthenticatedInquiriesIdRouteImport.update({
    id: '/inquiries/$id',
    path: '/inquiries/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVerificationRoute =
  AuthenticatedAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPortfolioReportsRoute =
  AuthenticatedAdminPortfolioReportsRouteImport.update({
    id: '/portfolio-reports',
    path: '/portfolio-reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPhotographersRoute =
  AuthenticatedAdminPhotographersRouteImport.update({
    id: '/photographers',
    path: '/photographers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImageryRoute =
  AuthenticatedAdminImageryRouteImport.update({
    id: '/imagery',
    path: '/imagery',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGenresRoute =
  AuthenticatedAdminGenresRouteImport.update({
    id: '/genres',
    path: '/genres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeaturedRoute =
  AuthenticatedAdminFeaturedRouteImport.update({
    id: '/featured',
    path: '/featured',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claim-account': typeof ClaimAccountRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/for-photographers': typeof ForPhotographersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/gigs/$id': typeof GigsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/featured': typeof AuthenticatedAdminFeaturedRoute
  '/admin/genres': typeof AuthenticatedAdminGenresRoute
  '/admin/imagery': typeof AuthenticatedAdminImageryRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/photographers': typeof AuthenticatedAdminPhotographersRoute
  '/admin/portfolio-reports': typeof AuthenticatedAdminPortfolioReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/inquiries/$id': typeof AuthenticatedInquiriesIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/studio/availability': typeof AuthenticatedStudioAvailabilityRoute
  '/studio/billing': typeof AuthenticatedStudioBillingRoute
  '/studio/bookings': typeof AuthenticatedStudioBookingsRoute
  '/studio/deliverables': typeof AuthenticatedStudioDeliverablesRoute
  '/studio/earnings': typeof AuthenticatedStudioEarningsRoute
  '/studio/gigs': typeof AuthenticatedStudioGigsRoute
  '/studio/leads': typeof AuthenticatedStudioLeadsRoute
  '/studio/packages': typeof AuthenticatedStudioPackagesRoute
  '/studio/portfolio': typeof AuthenticatedStudioPortfolioRoute
  '/studio/reviews': typeof AuthenticatedStudioReviewsRoute
  '/c/$category/$city': typeof CCategoryCityRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/inquiries/': typeof AuthenticatedInquiriesIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/claim-account': typeof ClaimAccountRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/for-photographers': typeof ForPhotographersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/gigs/$id': typeof GigsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/blog': typeof BlogIndexRoute
  '/gigs': typeof GigsIndexRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/featured': typeof AuthenticatedAdminFeaturedRoute
  '/admin/genres': typeof AuthenticatedAdminGenresRoute
  '/admin/imagery': typeof AuthenticatedAdminImageryRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/photographers': typeof AuthenticatedAdminPhotographersRoute
  '/admin/portfolio-reports': typeof AuthenticatedAdminPortfolioReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/inquiries/$id': typeof AuthenticatedInquiriesIdRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/studio/availability': typeof AuthenticatedStudioAvailabilityRoute
  '/studio/billing': typeof AuthenticatedStudioBillingRoute
  '/studio/bookings': typeof AuthenticatedStudioBookingsRoute
  '/studio/deliverables': typeof AuthenticatedStudioDeliverablesRoute
  '/studio/earnings': typeof AuthenticatedStudioEarningsRoute
  '/studio/gigs': typeof AuthenticatedStudioGigsRoute
  '/studio/leads': typeof AuthenticatedStudioLeadsRoute
  '/studio/packages': typeof AuthenticatedStudioPackagesRoute
  '/studio/portfolio': typeof AuthenticatedStudioPortfolioRoute
  '/studio/reviews': typeof AuthenticatedStudioReviewsRoute
  '/c/$category/$city': typeof CCategoryCityRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/inquiries': typeof AuthenticatedInquiriesIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/claim-account': typeof ClaimAccountRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faq': typeof FaqRoute
  '/for-photographers': typeof ForPhotographersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inspiration': typeof InspirationRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust-and-safety': typeof TrustAndSafetyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/gigs/$id': typeof GigsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/admin/featured': typeof AuthenticatedAdminFeaturedRoute
  '/_authenticated/admin/genres': typeof AuthenticatedAdminGenresRoute
  '/_authenticated/admin/imagery': typeof AuthenticatedAdminImageryRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/photographers': typeof AuthenticatedAdminPhotographersRoute
  '/_authenticated/admin/portfolio-reports': typeof AuthenticatedAdminPortfolioReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/verification': typeof AuthenticatedAdminVerificationRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/inquiries/$id': typeof AuthenticatedInquiriesIdRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/studio/availability': typeof AuthenticatedStudioAvailabilityRoute
  '/_authenticated/studio/billing': typeof AuthenticatedStudioBillingRoute
  '/_authenticated/studio/bookings': typeof AuthenticatedStudioBookingsRoute
  '/_authenticated/studio/deliverables': typeof AuthenticatedStudioDeliverablesRoute
  '/_authenticated/studio/earnings': typeof AuthenticatedStudioEarningsRoute
  '/_authenticated/studio/gigs': typeof AuthenticatedStudioGigsRoute
  '/_authenticated/studio/leads': typeof AuthenticatedStudioLeadsRoute
  '/_authenticated/studio/packages': typeof AuthenticatedStudioPackagesRoute
  '/_authenticated/studio/portfolio': typeof AuthenticatedStudioPortfolioRoute
  '/_authenticated/studio/reviews': typeof AuthenticatedStudioReviewsRoute
  '/c/$category/$city': typeof CCategoryCityRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/inquiries/': typeof AuthenticatedInquiriesIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/claim-account'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/for-photographers'
    | '/how-it-works'
    | '/inspiration'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-and-safety'
    | '/admin'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/saved'
    | '/blog/$slug'
    | '/gigs/$id'
    | '/p/$slug'
    | '/blog/'
    | '/gigs/'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cities'
    | '/admin/featured'
    | '/admin/genres'
    | '/admin/imagery'
    | '/admin/moderation'
    | '/admin/photographers'
    | '/admin/portfolio-reports'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/verification'
    | '/bookings/$id'
    | '/inquiries/$id'
    | '/messages/$conversationId'
    | '/studio/availability'
    | '/studio/billing'
    | '/studio/bookings'
    | '/studio/deliverables'
    | '/studio/earnings'
    | '/studio/gigs'
    | '/studio/leads'
    | '/studio/packages'
    | '/studio/portfolio'
    | '/studio/reviews'
    | '/c/$category/$city'
    | '/admin/'
    | '/bookings/'
    | '/inquiries/'
    | '/messages/'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/claim-account'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/for-photographers'
    | '/how-it-works'
    | '/inspiration'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-and-safety'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/saved'
    | '/blog/$slug'
    | '/gigs/$id'
    | '/p/$slug'
    | '/blog'
    | '/gigs'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/cities'
    | '/admin/featured'
    | '/admin/genres'
    | '/admin/imagery'
    | '/admin/moderation'
    | '/admin/photographers'
    | '/admin/portfolio-reports'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/verification'
    | '/bookings/$id'
    | '/inquiries/$id'
    | '/messages/$conversationId'
    | '/studio/availability'
    | '/studio/billing'
    | '/studio/bookings'
    | '/studio/deliverables'
    | '/studio/earnings'
    | '/studio/gigs'
    | '/studio/leads'
    | '/studio/packages'
    | '/studio/portfolio'
    | '/studio/reviews'
    | '/c/$category/$city'
    | '/admin'
    | '/bookings'
    | '/inquiries'
    | '/messages'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/claim-account'
    | '/contact'
    | '/cookie-policy'
    | '/faq'
    | '/for-photographers'
    | '/how-it-works'
    | '/inspiration'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/trust-and-safety'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/saved'
    | '/blog/$slug'
    | '/gigs/$id'
    | '/p/$slug'
    | '/blog/'
    | '/gigs/'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/featured'
    | '/_authenticated/admin/genres'
    | '/_authenticated/admin/imagery'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/photographers'
    | '/_authenticated/admin/portfolio-reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/verification'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/inquiries/$id'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/studio/availability'
    | '/_authenticated/studio/billing'
    | '/_authenticated/studio/bookings'
    | '/_authenticated/studio/deliverables'
    | '/_authenticated/studio/earnings'
    | '/_authenticated/studio/gigs'
    | '/_authenticated/studio/leads'
    | '/_authenticated/studio/packages'
    | '/_authenticated/studio/portfolio'
    | '/_authenticated/studio/reviews'
    | '/c/$category/$city'
    | '/_authenticated/admin/'
    | '/_authenticated/bookings/'
    | '/_authenticated/inquiries/'
    | '/_authenticated/messages/'
    | '/_authenticated/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ClaimAccountRoute: typeof ClaimAccountRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FaqRoute: typeof FaqRoute
  ForPhotographersRoute: typeof ForPhotographersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InspirationRoute: typeof InspirationRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustAndSafetyRoute: typeof TrustAndSafetyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GigsIdRoute: typeof GigsIdRoute
  PSlugRoute: typeof PSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GigsIndexRoute: typeof GigsIndexRoute
  CCategoryCityRoute: typeof CCategoryCityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust-and-safety': {
      id: '/trust-and-safety'
      path: '/trust-and-safety'
      fullPath: '/trust-and-safety'
      preLoaderRoute: typeof TrustAndSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-photographers': {
      id: '/for-photographers'
      path: '/for-photographers'
      fullPath: '/for-photographers'
      preLoaderRoute: typeof ForPhotographersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim-account': {
      id: '/claim-account'
      path: '/claim-account'
      fullPath: '/claim-account'
      preLoaderRoute: typeof ClaimAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/': {
      id: '/gigs/'
      path: '/gigs'
      fullPath: '/gigs/'
      preLoaderRoute: typeof GigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/gigs/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries/': {
      id: '/_authenticated/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof AuthenticatedInquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/c/$category/$city': {
      id: '/c/$category/$city'
      path: '/c/$category/$city'
      fullPath: '/c/$category/$city'
      preLoaderRoute: typeof CCategoryCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio/reviews': {
      id: '/_authenticated/studio/reviews'
      path: '/studio/reviews'
      fullPath: '/studio/reviews'
      preLoaderRoute: typeof AuthenticatedStudioReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/portfolio': {
      id: '/_authenticated/studio/portfolio'
      path: '/studio/portfolio'
      fullPath: '/studio/portfolio'
      preLoaderRoute: typeof AuthenticatedStudioPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/packages': {
      id: '/_authenticated/studio/packages'
      path: '/studio/packages'
      fullPath: '/studio/packages'
      preLoaderRoute: typeof AuthenticatedStudioPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/leads': {
      id: '/_authenticated/studio/leads'
      path: '/studio/leads'
      fullPath: '/studio/leads'
      preLoaderRoute: typeof AuthenticatedStudioLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/gigs': {
      id: '/_authenticated/studio/gigs'
      path: '/studio/gigs'
      fullPath: '/studio/gigs'
      preLoaderRoute: typeof AuthenticatedStudioGigsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/earnings': {
      id: '/_authenticated/studio/earnings'
      path: '/studio/earnings'
      fullPath: '/studio/earnings'
      preLoaderRoute: typeof AuthenticatedStudioEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/deliverables': {
      id: '/_authenticated/studio/deliverables'
      path: '/studio/deliverables'
      fullPath: '/studio/deliverables'
      preLoaderRoute: typeof AuthenticatedStudioDeliverablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/bookings': {
      id: '/_authenticated/studio/bookings'
      path: '/studio/bookings'
      fullPath: '/studio/bookings'
      preLoaderRoute: typeof AuthenticatedStudioBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/billing': {
      id: '/_authenticated/studio/billing'
      path: '/studio/billing'
      fullPath: '/studio/billing'
      preLoaderRoute: typeof AuthenticatedStudioBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/availability': {
      id: '/_authenticated/studio/availability'
      path: '/studio/availability'
      fullPath: '/studio/availability'
      preLoaderRoute: typeof AuthenticatedStudioAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries/$id': {
      id: '/_authenticated/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/inquiries/$id'
      preLoaderRoute: typeof AuthenticatedInquiriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/verification': {
      id: '/_authenticated/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AuthenticatedAdminVerificationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/portfolio-reports': {
      id: '/_authenticated/admin/portfolio-reports'
      path: '/portfolio-reports'
      fullPath: '/admin/portfolio-reports'
      preLoaderRoute: typeof AuthenticatedAdminPortfolioReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/photographers': {
      id: '/_authenticated/admin/photographers'
      path: '/photographers'
      fullPath: '/admin/photographers'
      preLoaderRoute: typeof AuthenticatedAdminPhotographersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/imagery': {
      id: '/_authenticated/admin/imagery'
      path: '/imagery'
      fullPath: '/admin/imagery'
      preLoaderRoute: typeof AuthenticatedAdminImageryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/genres': {
      id: '/_authenticated/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AuthenticatedAdminGenresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/featured': {
      id: '/_authenticated/admin/featured'
      path: '/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AuthenticatedAdminFeaturedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cities': {
      id: '/_authenticated/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminFeaturedRoute: typeof AuthenticatedAdminFeaturedRoute
  AuthenticatedAdminGenresRoute: typeof AuthenticatedAdminGenresRoute
  AuthenticatedAdminImageryRoute: typeof AuthenticatedAdminImageryRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminPhotographersRoute: typeof AuthenticatedAdminPhotographersRoute
  AuthenticatedAdminPortfolioReportsRoute: typeof AuthenticatedAdminPortfolioReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminVerificationRoute: typeof AuthenticatedAdminVerificationRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
  AuthenticatedAdminFeaturedRoute: AuthenticatedAdminFeaturedRoute,
  AuthenticatedAdminGenresRoute: AuthenticatedAdminGenresRoute,
  AuthenticatedAdminImageryRoute: AuthenticatedAdminImageryRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminPhotographersRoute: AuthenticatedAdminPhotographersRoute,
  AuthenticatedAdminPortfolioReportsRoute:
    AuthenticatedAdminPortfolioReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminVerificationRoute: AuthenticatedAdminVerificationRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedInquiriesIdRoute: typeof AuthenticatedInquiriesIdRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedStudioAvailabilityRoute: typeof AuthenticatedStudioAvailabilityRoute
  AuthenticatedStudioBillingRoute: typeof AuthenticatedStudioBillingRoute
  AuthenticatedStudioBookingsRoute: typeof AuthenticatedStudioBookingsRoute
  AuthenticatedStudioDeliverablesRoute: typeof AuthenticatedStudioDeliverablesRoute
  AuthenticatedStudioEarningsRoute: typeof AuthenticatedStudioEarningsRoute
  AuthenticatedStudioGigsRoute: typeof AuthenticatedStudioGigsRoute
  AuthenticatedStudioLeadsRoute: typeof AuthenticatedStudioLeadsRoute
  AuthenticatedStudioPackagesRoute: typeof AuthenticatedStudioPackagesRoute
  AuthenticatedStudioPortfolioRoute: typeof AuthenticatedStudioPortfolioRoute
  AuthenticatedStudioReviewsRoute: typeof AuthenticatedStudioReviewsRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedInquiriesIndexRoute: typeof AuthenticatedInquiriesIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedInquiriesIdRoute: AuthenticatedInquiriesIdRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedStudioAvailabilityRoute: AuthenticatedStudioAvailabilityRoute,
  AuthenticatedStudioBillingRoute: AuthenticatedStudioBillingRoute,
  AuthenticatedStudioBookingsRoute: AuthenticatedStudioBookingsRoute,
  AuthenticatedStudioDeliverablesRoute: AuthenticatedStudioDeliverablesRoute,
  AuthenticatedStudioEarningsRoute: AuthenticatedStudioEarningsRoute,
  AuthenticatedStudioGigsRoute: AuthenticatedStudioGigsRoute,
  AuthenticatedStudioLeadsRoute: AuthenticatedStudioLeadsRoute,
  AuthenticatedStudioPackagesRoute: AuthenticatedStudioPackagesRoute,
  AuthenticatedStudioPortfolioRoute: AuthenticatedStudioPortfolioRoute,
  AuthenticatedStudioReviewsRoute: AuthenticatedStudioReviewsRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedInquiriesIndexRoute: AuthenticatedInquiriesIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ClaimAccountRoute: ClaimAccountRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FaqRoute: FaqRoute,
  ForPhotographersRoute: ForPhotographersRoute,
  HowItWorksRoute: HowItWorksRoute,
  InspirationRoute: InspirationRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustAndSafetyRoute: TrustAndSafetyRoute,
  BlogSlugRoute: BlogSlugRoute,
  GigsIdRoute: GigsIdRoute,
  PSlugRoute: PSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GigsIndexRoute: GigsIndexRoute,
  CCategoryCityRoute: CCategoryCityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
